// <auto-generated> Docs/art_refs/tidekelp/make_tidekelp.py пишет этот файл вместе с листом.
// Перерисовал плоды руками — поправь смещения здесь и больше не запускай генератор
// (или перенеси правки в него).
using Microsoft.Xna.Framework;

namespace SoA.Content.Tiles.Nature
{
    public partial class Tidekelp_tile
    {
        // Ореолы плодов: вид, форма, смещение центра плода от низа-центра сегмента
        // (до поворота), поперечник ореола в px
        private static readonly Bloom[] Blooms =
        {
            new(0, 3, new Vector2(-17f, 4f), 22f),
            new(0, 5, new Vector2(15f, 4f), 22f),
            new(0, 7, new Vector2(-15f, 2f), 22f),
            new(0, 8, new Vector2(-9f, 4f), 22f),
            new(0, 8, new Vector2(9f, 6f), 22f),
            new(1, 3, new Vector2(-17f, 4f), 17f),
            new(1, 5, new Vector2(15f, 4f), 17f),
            new(1, 8, new Vector2(-9f, 4f), 17f),
            new(1, 8, new Vector2(9f, 6f), 17f),
            new(2, 3, new Vector2(-17f, 6f), 28f),
            new(2, 5, new Vector2(15f, 6f), 28f),
            new(2, 7, new Vector2(-15f, 4f), 28f),
            new(2, 8, new Vector2(-9f, 6f), 28f),
            new(2, 8, new Vector2(9f, 8f), 28f),
        };
    }
}
