// <auto-generated> Docs/art_refs/tidekelp/make_kelp_atlas.py пишет этот файл вместе с атласом.
// Перерисовываешь атлас руками — области не двигай (или поправь их здесь).
using Microsoft.Xna.Framework;

namespace SoA.Common.Graphics.Kelp
{
    // Области атласа подводного леса, в арт-пикселях (1 тексель = 2x2 пикселя мира)
    internal static class KelpAtlas
    {
        public const int Width = 128;
        public const int Height = 61;

        // Полосы стеблей: [вид * 2 + план], план 0 — ближний, 1 — дальний. Повторяются по вертикали
        public static readonly Rectangle[] Stems =
        {
            new(32, 1, 12, 24), new(45, 1, 6, 24),
            new(80, 1, 6, 20), new(87, 1, 4, 20),
            new(1, 36, 12, 18), new(14, 36, 8, 18)
        };

        // Листья: [вид][вариант], основанием вниз, свет на левой (наружной) кромке
        public static readonly Rectangle[][] Leaves =
        {
            new Rectangle[] { new(12, 1, 9, 30), new(1, 1, 10, 34), new(52, 1, 8, 24), new(22, 1, 9, 27), new(33, 36, 6, 17) },
            new Rectangle[] { new(92, 1, 6, 20), new(61, 1, 7, 24), new(40, 36, 6, 16), new(56, 36, 5, 14), new(109, 1, 6, 18) },
            new Rectangle[] { new(99, 1, 9, 20), new(69, 1, 10, 24), new(47, 36, 8, 16), new(23, 36, 9, 18), new(62, 36, 7, 13) }
        };

        // Плоды: малый, средний, крупный. Хвостик крепится к середине верхней строки
        public static readonly Rectangle[] Fruits = { new(120, 36, 4, 5), new(96, 36, 5, 6), new(70, 36, 6, 7) };

        public static readonly Rectangle Stalk = new(102, 36, 2, 6);

        public static readonly Rectangle[] Rocks = { new(105, 36, 14, 6), new(77, 36, 18, 7), new(1, 55, 12, 5) };
    }
}
